### ISSUE TITLE
Other Payment plans

### ISSUE THREAD

**Issue by mirmibrahim** [aamnah/easypaisa#1]
hey i have integrated your code but it only goes for a phone number that has to be displayed in the end. How can we integrate the easy paisa payment option like credit /debit card one ?

**Comment by aamnah** [comment]
You mean **Easypay**? You should contact Easypay support for that. As per their [website](https://www.easypaisa.com.pk/corporate/easypay-online-for-business), they have OpenCart plugin available.

**Comment by mirmibrahim** [comment]
BTW thanks

**Comment by aamnah** [comment]
You're welcome
