### ISSUE TITLE
Easypaisa Api

### ISSUE THREAD

**Issue by naumanahmed19** [aamnah/easypaisa#2]
Hello Aamnah,

Can you please tell me where I can find easypaisa api documentation. I want to integrate it on my website.

Thanks.

**Comment by aamnah** [comment]
You mean **Easypay** API docs? You should contact Easypay [support](https://www.easypaisa.com.pk/corporate/easypay-online-for-business) for that.

**Comment by naumanahmed19** [comment]
Yes. Thanks for reply

**Comment by aamnah** [comment]
No problem.
