### ISSUE TITLE
Installed in 2.3 OC

### ISSUE THREAD

**Issue by seansmith1** [aamnah/easypaisa#3]
Notice: Error: Could not load template /home/footinso/public_html/catalog/view/theme/default/template/default/template/payment/easypaisa.tpl! in /home/footinso/public_html/system/storage/modification/system/library/template/basic.php on line 26
Selected easypaisa while checkout, getting this error. 

I installed it from DRAg n DROP.

**Comment by seansmith1** [comment]
How can change the Path default/template/ as it is repeating. and i am NOT using Default Template.

**Comment by aamnah** [comment]
Current compatibility is 2.1.x so i wouldn't be surprised if installing on 2.3.x gives any errors.. I can look into upgrading the extension but no guarantees..

**Comment by aamnah** [comment]
Also, i just tested on 2.3.0.2 and not getting the error on checkout. Can you please share a screenshot?

**Comment by seansmith1** [comment]
Thank you ,that would be great, I tried changing Path from default/template/payment/easypaisa.tpl to 
/payment/easypaisa.tpl it removed that error but after confirming the order, I get this on the next success screen

http://www.footinsole.com/index.php?route=checkout/success

Parse error: syntax error, unexpected '<' in /home/footinso/public_html/catalog/view/theme/pav_krstore/template/common/success.tpl on line 64

**Comment by seansmith1** [comment]
i receive the order though in the admin , but custom see this error

**Comment by seansmith1** [comment]
http://imgur.com/a/uOEe5

Screenshot.

I have this in Success.tpl file on line 64

	
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = xxxxxxxxxxx;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "bxPDCJ7MrnEQgam0mwM";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/862786689/?label=bxPDCJ7MrnEQgam0mwM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

?>
<?php echo $footer; ?>

**Comment by seansmith1** [comment]
i use theme (pav_krstore) ,

**Comment by aamnah** [comment]
Download the latest release for OC 2.3 from [here](https://github.com/aamnah/easypaisa/releases/tag/OC2.3.x)

**Comment by aamnah** [comment]
You may also need to delete the folders created when you installed the incompatible 2.1 version of the extension:

- admin/controller/payment
- admin/view/template/payment
- admin/language/english
- catalog/controller/payment
- catalog/language/english
- catalog/model/payment
- catalog/view/theme/default/template/payment

The major difference between the two OpenCart versions is directory structure.. `payment` folder is now `extension/payment` and language folder has been renamed from `english` to `en-gb`

Good luck!
