### ISSUE TITLE
easypaisa integration in node.js

### ISSUE THREAD

**Issue by zohaibalishah** [aamnah/easypaisa#4]
Hello mam, hope you are doing well i have seen your code its amzaing but unfortunately i need this to integrate it into my node.js if you could guide me in this regard will be very thankful. 
regards,
Zohaib ali shah

**Comment by aamnah** [comment]
Hi Zohaib,

You're probably looking for *easypay* merchant account integration and not
easypaisa. Easypaisa would include just showing the account details for
sending money, which i'm sure you can easily handle. For easypay, you'd
need a merchant account and would need to communicate with some API.

The API documentation for easypay is not publicly available. However, this
guy <https://github.com/shaan360/telenor-easypay> seems to have some code..

Hope that helps. Good luck!

**Comment by khanakhun** [comment]
Hi , 
i want to ask that if it's  possible to integrate easypaisa online payment gateway using Nodejs instead Php
thanks

**Comment by faizankazmi** [comment]
@aamnah  Dear Aamnah Hope you are doing well I am facing the error **Parameter Authentication failed.**
 but i am sending correct parameters already/ any help?

**Comment by MuhammadAdnan2** [comment]
Hi @zohaibalishah , You have implemented easypaisa in node js. If yes then share code with me . Thanks

**Comment by hamzazafarHW** [comment]
have anyone done easypaisa with react native then please help me out

**Comment by zohaibalishah** [comment]
Yes you need to contact with easypaisa they provide you JSON api you just
need to integrate with with app or web.

**Comment by Ali-TM-original** [comment]
> have anyone done easypaisa with react native then please help me out

Its pretty similar to that of the web tbh you use a webview or just simple axios to send a post request to ep rest api. This helped me alot explains everything in details https://stackoverflow.com/questions/62818901/easypaisa-integration-in-react-native

**Comment by eman-zafar** [comment]
does anyone have integrated easypaisa in MERN?if yes, please let me know

**Comment by who-is-mozzam** [comment]
does it possible to accept payment without having a merchant account ?

**Comment by Ali-TM-original** [comment]
> does it possible to accept payment without having a merchant account ?

Nope, you must have a merchant account for it

**Comment by abhanan369** [comment]
I'm trying to integrate easypaisa and jazzcash with nodejs. Can someone help me in this
